export const CATALOG = [
  {
    id: "poco-c71-blue-64-4",
    name: "POCO C71 (Cool Blue, 64 GB) 4 GB RAM",
    price: 6399,
    mrp: 8999,
    tags: ["Mobile", "POCO", "C71"],
    color: "Cool Blue",
    capacity: "4 GB + 64 GB",
    stock: true,
  },
  {
    id: "samsung-m14-128-6",
    name: "Samsung Galaxy M14 (Navy Blue, 128 GB) 6 GB RAM",
    price: 11999,
    mrp: 14999,
    tags: ["Mobile", "Samsung", "M14"],
    color: "Navy Blue",
    capacity: "6 GB + 128 GB",
    stock: true,
  },
  {
    id: "lg-dualinv-ac-1-5t",
    name: "LG 1.5 Ton 5 Star Dual Inverter AC",
    price: 36990,
    mrp: 50990,
    tags: ["AC", "LG", "Home Appliance"],
    color: "White",
    capacity: "1.5 Ton",
    stock: true,
  },
  {
    id: "whirlpool-340l-fridge",
    name: "Whirlpool 340 L Frost Free Refrigerator",
    price: 29990,
    mrp: 35990,
    tags: ["Refrigerator", "Whirlpool"],
    color: "Steel",
    capacity: "340 L",
    stock: true,
  },
  {
    id: "dyson-v12-detect",
    name: "Dyson V12 Detect Slim Vacuum Cleaner",
    price: 42990,
    mrp: 52990,
    tags: ["Vacuum", "Dyson", "Home"],
    color: "Grey",
    capacity: "Slim",
    stock: true,
  },
];
